name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - exp
      - main
      - feature/**
    tags: ["**"]

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Run test
        run: make _test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Run lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61
          args: --timeout=5m

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Build
        env:
          GOOS: linux
          GOARCH: arm64
        run: make _build

  build-and-push-image:
    if: github.ref == 'refs/heads/exp' || startsWith(github.ref, 'refs/heads/feature/') || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs:
      - test
      - lint
      - build
    steps:
      - uses: actions/checkout@v4

      - name: Get 10 length commit sha
        if: github.ref == 'refs/heads/exp' || startsWith(github.ref, 'refs/heads/feature/')
        id: short-sha
        run: |
          echo value=$(echo ${{ github.sha }} | cut -c1-10) >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,priority=100,prefix=exp-,value=${{ steps.short-sha.outputs.value }},enable=${{ startsWith(github.ref, 'refs/heads/exp') }}
            type=raw,priority=100,prefix=feature-,value=${{ steps.short-sha.outputs.value }},enable=${{ startsWith(github.ref, 'refs/heads/feature/') }}
            type=ref,priority=600,event=tag,enable=${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Get current time
        id: time
        shell: sh
        run: |
          echo current_time=$(TZ=Asia/Seoul date +'%Y-%m-%dT%H:%M:%S%z') >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/arm64
          build-args: |
            BUILD_VERSION=${{ github.ref_name }}
            BUILD_COMMIT=${{ github.sha }}
            BUILD_TIME=${{ steps.time.outputs.current_time }}
